# Generated by Django 6.0.1 on 2026-01-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_allow_spaces_username'),
        ('users', '0002_user_otp_code'),
    ]

    operations = [
    ]
