# Generated by Django 6.0.1 on 2026-01-21 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('medical_conditions', models.JSONField(default=list)),
                ('allergies', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('risk_analysis_result', models.JSONField(blank=True, null=True)),
                ('pharmacist_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='prescriptions.prescription')),
            ],
        ),
    ]
