# Generated by Django 6.0.1 on 2026-01-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_chosen_alternative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
